kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: minikube-namespace-creator
  namespace: default
subjects:
- kind: User
  name: minikube
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: namespace-creator
  apiGroup: rbac.authorization.k8s.io
